# -*- coding: utf-8 -*-
"""download_Data_v01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w1OND5jZy819_zomCHd8Hs7RnHU8tKrR
"""

import requests
import os

'''
Escolha a data e hora para plotar o mapa,
mas lembre, o METAR só guarda os dados de até um mês e o GFS uma semana.
'''

dia = '10'
mes = '06'
ano = '2024'
hora = '18'

print(f'Estou fazendo a carta deste dia ({dia}/{mes}/{ano}) as {hora} UTC')

# Construa o URL do METAR com a hora arredondada
metar_url = f"https://thredds.ucar.edu/thredds/fileServer/noaaport/text/metar/metar_{ano}{mes}{dia}_{hora}00.txt"
print(metar_url)
# Agora, você pode usar a variável metar_url para baixar o METAR no horário desejado.
print(f'A URL do METAR no horário desejado é: {ano}{mes}{dia}{hora}00')

# Faz o download do arquivo
urllib.request.urlretrieve(metar_url, "metar_data.txt")

#-----------------------------------------------------------------------------------------------------------
#Author: Vitor Tenório
#-----------------------------------------------------------------------------------------------------------

# Start the time counter
start_time = t.time()

print('---------------------------------------')
print('GFS Download (NOMADS) - Script started.')
print('---------------------------------------')

#-----------------------------------------------------------------------------------------------------------
# Download directory
dir = "Samples"; os.makedirs(dir, exist_ok=True)

#Vou pegar com resolução de 25KM
resolution = '25'

# Desired extent
min_lon = '-100.00'
max_lon = '-20.00'
min_lat = '-65.00'
max_lat = '15.00'

# Construir o URL
url = f'https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p{resolution}.pl?dir=%2Fgfs.{ano}{mes}{dia}%2F{hora}%2Fatmos&file=gfs.t{hora}z.pgrb2.0p{resolution}.f000&all_var=on&all_lev=on&subregion=&toplat={max_lat}&leftlon={min_lon}&rightlon={max_lon}&bottomlat={min_lat}'
print(url)

# Nome do arquivo a ser baixado
file_name = f'gfs.t{ano}{dia}{hora}z.pgrb2.0p{resolution}.f000'

# Print do nome do arquivo
print("File name: ", file_name)

# Envio da requisição GET para baixar o arquivo
myfile = requests.get(url)

# Download do arquivo
open(os.path.join(dir, file_name), 'wb').write(myfile.content)

# Printando a data e hora do download
print('\n---------------------')
print('Downloading GFS File:')
print('---------------------')
print('Resolution: ' + resolution)
print(f'Date: {dia}/{mes}/{ano}')
print(f'Run: {hora}')

#-----------------------------------------------------------------------------------------------------------

# End the time counter
print('\nTotal Processing Time:', round((t.time() - start_time),2), 'seconds.')
