name: Executar Script Python download Data

on:
  schedule:
    # Agendar para rodar às 00:00, 06:00, 12:00 e 18:00 UTC todos os dias
    - cron: '0 4 05 * *'
    - cron: '0 10 05 * *'
    - cron: '0 16 05 * *'
    - cron: '0 22 05 * *'
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install matplotlib
        pip install pygrib
        pip install cartopy
        pip install metpy
        pip install netCDF4
        pip install siphon
        apt-get install libproj-dev proj-data proj-bin
        apt-get install libgeos-dev
        pip install cartopy
        apt-get -qq install python-cartopy python3-cartopy
        pip uninstall -y shapely
        pip install geopandas
        apt-get install libeccodes-dev libproj-dev
        pip install importlib-metadata==4.13.0
        pip install cfgrib
        pip install ecCodes
        pip install xarray
        pip install numpy
        pip install wrf-python==1.3.4.1

    - name: Run script
      run: |
        python scripts/data/carta_sinotica.py
